import type {
  AppSnapshot,
  LiveCallConfigSnapshot,
  LiveCallStateSnapshot,
  CardCustomizationSnapshot,
  FeedSnapshot,
  GameSnapshot,
  LiveSnapshot,
  MarketplaceSnapshot,
  PresenceSnapshot,
} from '@/lib/app-types'

const previewRoomCatalog = {
  'preview-room-alpha': 'Mesa Preview Central',
  'preview-room-bots': 'Mesa vs Bots',
  'preview-room-ranked': 'Ranked Preview',
  'preview-room-private': 'Sala Privada Demo',
} as const

type PreviewState = PresenceSnapshot['state']

function getPreviewRoomName(roomId?: string | null) {
  if (roomId && roomId in previewRoomCatalog) {
    return previewRoomCatalog[roomId as keyof typeof previewRoomCatalog]
  }

  return previewRoomCatalog['preview-room-alpha']
}

export function getPreviewPresence(params?: {
  state?: PreviewState
  screen?: string | null
  latencyMs?: number | null
}): PresenceSnapshot & { onlineUsersCount: number } {
  const state = params?.state ?? 'online'

  return {
    state,
    label: state === 'offline' ? 'Preview offline' : state === 'away' ? 'Preview en pausa' : 'Preview activo',
    onlineUsers: '6',
    onlineUsersCount: 6,
    latencyMs: params?.latencyMs ?? 18,
    currentScreen: params?.screen ?? 'home',
  }
}

export function getPreviewLiveSnapshot(streamId?: string): LiveSnapshot {
  const streams = [
    {
      id: 'preview-stream-main',
      streamer: {
        name: 'LunaGamer',
        avatar: 'lunagamer',
        level: 58,
        followers: 12500,
        isVerified: true,
      },
      title: 'Preview del hub social gaming en vivo',
      game: 'Mesa Clasica',
      viewers: 3420,
      likes: 1240,
      comments: 342,
      thumbnail: 'pulse',
      isLive: true,
      tags: ['preview', 'hub', 'mesa'],
      roomName: 'Mesa Preview Central',
      statusLine: 'Vista previa del modulo live sin backend conectado.',
    },
    {
      id: 'preview-stream-secondary',
      streamer: {
        name: 'CyberQueen',
        avatar: 'cyberqueen',
        level: 67,
        followers: 45000,
        isVerified: true,
      },
      title: 'Tour del marketplace y card lab',
      game: 'Creator Studio',
      viewers: 1180,
      likes: 820,
      comments: 104,
      thumbnail: 'diamond',
      isLive: true,
      tags: ['addons', 'cardlab'],
      roomName: 'Card Lab Preview',
      statusLine: 'Segundo stream de muestra para revisar navegacion.',
    },
  ]

  const activeStreamId = streams.some((candidate) => candidate.id === streamId) ? streamId ?? streams[0].id : streams[0].id

  return {
    activeStreamId,
    streams,
    chatMessages: [
      {
        id: 'preview-live-chat-1',
        user: 'MiaGamer',
        message: 'Se ve bien el hub general.',
        color: 'text-cyan-400',
        timestamp: '10:31',
      },
      {
        id: 'preview-live-chat-2',
        user: 'Yo',
        message: 'Estamos revisando exactamente que ya existe.',
        color: 'text-fuchsia-400',
        timestamp: '10:32',
        isMe: true,
      },
      {
        id: 'preview-live-chat-3',
        user: 'SamuraiQ',
        message: 'Falta conectar la persistencia real para cerrar el loop.',
        color: 'text-yellow-400',
        timestamp: '10:33',
      },
    ],
    gifts: [
      {
        id: 'preview-gift-1',
        senderName: 'CyberQueen',
        itemName: 'Pulse',
        image: 'pulse',
        quantity: 3,
        valueLabel: '300 coins',
        createdAt: 'Hace 2 min',
      },
      {
        id: 'preview-gift-2',
        senderName: 'Nova',
        itemName: 'Diamond',
        image: 'diamond',
        quantity: 1,
        valueLabel: '25 gems',
        createdAt: 'Hace 5 min',
      },
    ],
    clips: [
      {
        id: 'preview-clip-1',
        title: 'Quick match del hub',
        duration: '0:42',
        viewsLabel: '12.4K',
        accent: 'from-violet-500/30 to-fuchsia-500/20',
      },
      {
        id: 'preview-clip-2',
        title: 'Card lab walkthrough',
        duration: '1:18',
        viewsLabel: '8.1K',
        accent: 'from-cyan-500/30 to-sky-500/20',
      },
    ],
    creator: {
      displayName: 'AlexRey30',
      username: '@rey30verse',
      roleLine: 'Founder • Streamer • Designer',
      followers: '25.8K',
      level: '42',
      goalLabel: 'Cerrar base productiva',
      goalProgress: '72%',
      highlightNote: 'Preview navegable para revisar modulos actuales.',
    },
    giftOptions: [
      { id: 'preview-gift-option-1', name: 'Pulse', price: 100, currency: 'coins', image: 'pulse', ownedQuantity: 4, canSend: true, helperText: 'Inventario: x4' },
      { id: 'preview-gift-option-2', name: 'Diamond', price: 25, currency: 'gems', image: 'diamond', ownedQuantity: 0, canSend: true, helperText: '25 gems' },
      { id: 'preview-gift-option-3', name: 'Crown', price: 320, currency: 'coins', image: 'crown', ownedQuantity: 0, canSend: false, helperText: '320 coins' },
    ],
    wallet: {
      coins: '12.4K',
      gems: '250',
    },
  }
}

export function getPreviewLiveCallState(streamId?: string): LiveCallStateSnapshot {
  return {
    streamId: streamId ?? 'preview-stream-main',
    streamTitle: 'Preview Live Call',
    rtcEnabled: false,
    note: 'La videollamada WebRTC solo está disponible fuera de preview.',
    myParticipantId: null,
    participants: [],
  }
}

export function getPreviewLiveCallConfig(): LiveCallConfigSnapshot {
  return {
    rtcEnabled: false,
    mode: 'disabled',
    hasTurnServer: false,
    note: 'La configuración WebRTC real solo se expone fuera de preview.',
    iceServers: [],
  }
}

export function getPreviewFeedSnapshot(): FeedSnapshot {
  return {
    posts: [
      {
        id: 'preview-feed-post-1',
        content: 'El feed puede mostrar imagen destacada y comentarios en thread incluso en preview.',
        timestamp: 'Ahora',
        likes: 18,
        commentsCount: 3,
        isLikedByMe: true,
        author: {
          id: 'preview-user',
          name: 'AlexRey30',
          handle: 'alexrey30',
          avatar: 'alexrey30',
          level: 42,
          isMe: true,
        },
        media: [
          {
            id: 'preview-feed-media-1',
            url: '/logo.svg',
            mimeType: 'image/svg+xml',
            width: 256,
            height: 256,
            originalName: 'logo.svg',
          },
        ],
        comments: [
          {
            id: 'preview-feed-comment-1',
            content: 'Ya se siente mucho mejor ver el post con media real.',
            timestamp: '5 min',
            likes: 2,
            isLikedByMe: false,
            author: {
              id: 'preview-luna',
              name: 'LunaGamer',
              handle: 'lunagamer',
              avatar: 'lunagamer',
              level: 58,
            },
            replies: [
              {
                id: 'preview-feed-comment-2',
                content: 'Sí, y ahora también acepta respuestas dentro del mismo hilo.',
                timestamp: '2 min',
                likes: 1,
                isLikedByMe: true,
                author: {
                  id: 'preview-user',
                  name: 'AlexRey30',
                  handle: 'alexrey30',
                  avatar: 'alexrey30',
                  level: 42,
                  isMe: true,
                },
                replies: [],
              },
            ],
          },
          {
            id: 'preview-feed-comment-3',
            content: 'En local esto ya vive contra PostgreSQL.',
            timestamp: '1 min',
            likes: 0,
            isLikedByMe: false,
            author: {
              id: 'preview-cyber',
              name: 'CyberQueen',
              handle: 'cyberqueen',
              avatar: 'cyberqueen',
              level: 67,
            },
            replies: [],
          },
        ],
      },
    ],
  }
}

export function getPreviewMarketplaceSnapshot(): MarketplaceSnapshot {
  return {
    coins: '12.4K',
    gems: '250',
    items: [
      {
        id: 'preview-market-1',
        name: 'Nebula Deck',
        description: 'Baraja premium con degradado neon para el hub actual.',
        price: 450,
        currency: 'coins',
        image: 'neon',
        type: 'deck',
        rarity: 'rare',
        popular: true,
        ownedQuantity: 1,
        equipped: true,
        canEquip: true,
      },
      {
        id: 'preview-market-2',
        name: 'Cosmic Frame',
        description: 'Tema visual para cartas y paneles destacados.',
        price: 35,
        currency: 'gems',
        image: 'cosmic',
        type: 'theme',
        rarity: 'epic',
        new: true,
      },
      {
        id: 'preview-market-3',
        name: 'Pulse Gift',
        description: 'Regalo de stream para destacar mensajes.',
        price: 100,
        currency: 'coins',
        image: 'pulse',
        type: 'gift',
        rarity: 'common',
      },
      {
        id: 'preview-market-4',
        name: 'Founder Badge',
        description: 'Badge de prueba para perfiles y salas.',
        price: 20,
        currency: 'gems',
        image: 'crown',
        type: 'badge',
        rarity: 'legendary',
      },
    ],
    deckStyles: [
      { id: 'nebula', name: 'Nebula', colors: 'from-violet-500 to-cyan-500' },
      { id: 'aurora', name: 'Aurora', colors: 'from-cyan-500 to-emerald-400' },
      { id: 'obsidian', name: 'Obsidian', colors: 'from-zinc-700 to-zinc-950' },
    ],
    inventory: [
      { id: 'inventory-1', name: 'Nebula Deck', type: 'deck', quantity: 1, equipped: true, image: 'neon' },
      { id: 'inventory-2', name: 'Pulse Gift', type: 'gift', quantity: 4, image: 'pulse' },
      { id: 'inventory-3', name: 'Founder Badge', type: 'badge', quantity: 1, image: 'crown' },
    ],
  }
}

export function getPreviewCustomizationSnapshot(): CardCustomizationSnapshot {
  return {
    coins: '12.4K',
    gems: '250',
    activeDeckKey: 'default',
    deckOptions: [
      {
        key: 'default',
        name: 'Mazo global',
        styleId: null,
        isDefault: true,
        isEquipped: true,
      },
    ],
    deckComparisons: [
      {
        deckKey: 'default',
        deckName: 'Mazo global',
        isActive: true,
        isDefault: true,
        overrides: [],
      },
    ],
    styles: [
      { id: 'nebula', name: 'Nebula', colors: 'from-violet-500 to-cyan-500' },
      { id: 'aurora', name: 'Aurora', colors: 'from-cyan-500 to-emerald-400' },
      { id: 'royal', name: 'Royal Gold', colors: 'from-amber-300 to-orange-500' },
    ],
    templates: [
      {
        id: 'template-preview-1',
        name: 'Deck Neon',
        styleId: 'nebula',
        styleName: 'Nebula',
        scope: 'deck',
        targetCard: null,
        targetSuit: null,
        targetModule: null,
        targetElement: null,
        zoom: 100,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        isEquipped: true,
        artwork: null,
        updatedAt: 'Hoy',
      },
      {
        id: 'template-preview-2',
        name: 'Reina Cosmica',
        styleId: 'royal',
        styleName: 'Royal Gold',
        scope: 'card',
        targetCard: 'Q-spades',
        targetSuit: null,
        targetModule: null,
        targetElement: null,
        zoom: 112,
        rotation: -4,
        offsetX: 6,
        offsetY: -2,
        isEquipped: false,
        artwork: {
          id: 'artwork-preview-1',
          name: 'phase2-smoke-1774576390384.webp',
          url: '/uploads/card-lab/phase2-smoke-1774576390384.webp',
          provider: 'local',
          width: 1024,
          height: 1024,
        },
        updatedAt: 'Ayer',
      },
    ],
    visualOverrides: [],
    artworks: [
      {
        id: 'artwork-preview-1',
        name: 'phase2-smoke-1774576390384.webp',
        url: '/uploads/card-lab/phase2-smoke-1774576390384.webp',
        provider: 'local',
        width: 1024,
        height: 1024,
      },
      {
        id: 'artwork-preview-2',
        name: 'image-mar-26-2026-11-35-17-am.webp',
        url: '/uploads/card-lab/1774569022716-image-mar-26-2026-11-35-17-am.webp',
        provider: 'local',
        width: 768,
        height: 1024,
      },
    ],
    deckModules: [
      {
        id: 'element-fire',
        name: 'Fuego',
        type: 'elemental',
        element: 'fire',
        themeColor: '#ff4a1c',
        cards: 13,
        previewCards: [
          {
            id: 'element-fire-1',
            element: 'fire',
            moduleId: 'element-fire',
            type: 'elemental',
            rank: 1,
            label: '1',
            name: 'Fuego 1',
            themeColor: '#ff4a1c',
            accentColor: '#facc15',
          },
          {
            id: 'element-fire-7',
            element: 'fire',
            moduleId: 'element-fire',
            type: 'elemental',
            rank: 7,
            label: '7',
            name: 'Fuego 7',
            themeColor: '#ff4a1c',
            accentColor: '#facc15',
          },
          {
            id: 'element-fire-13',
            element: 'fire',
            moduleId: 'element-fire',
            type: 'elemental',
            rank: 13,
            label: '13',
            name: 'Fuego 13',
            themeColor: '#ff4a1c',
            accentColor: '#facc15',
          },
        ],
        effects: [
          {
            id: 'fire-scorch',
            name: 'Scorch',
            description: 'Las cartas de fuego suman +2 pts al choque.',
            trigger: 'on-score',
            scoreModifier: 2,
            priority: 10,
          },
        ],
      },
      {
        id: 'element-water',
        name: 'Agua',
        type: 'elemental',
        element: 'water',
        themeColor: '#0ea5e9',
        cards: 13,
        previewCards: [
          {
            id: 'element-water-1',
            element: 'water',
            moduleId: 'element-water',
            type: 'elemental',
            rank: 1,
            label: '1',
            name: 'Agua 1',
            themeColor: '#0ea5e9',
            accentColor: '#67e8f9',
          },
          {
            id: 'element-water-7',
            element: 'water',
            moduleId: 'element-water',
            type: 'elemental',
            rank: 7,
            label: '7',
            name: 'Agua 7',
            themeColor: '#0ea5e9',
            accentColor: '#67e8f9',
          },
          {
            id: 'element-water-13',
            element: 'water',
            moduleId: 'element-water',
            type: 'elemental',
            rank: 13,
            label: '13',
            name: 'Agua 13',
            themeColor: '#0ea5e9',
            accentColor: '#67e8f9',
          },
        ],
        effects: [
          {
            id: 'water-flow',
            name: 'Flow',
            description: 'Las cartas de agua suavizan el choque con -1 pt.',
            trigger: 'on-score',
            scoreModifier: -1,
            actions: [
              {
                type: 'protect-points',
                target: 'self',
                value: 3,
                label: 'Escudo de agua',
              },
            ],
            priority: 20,
          },
        ],
      },
    ],
    creatorCard: {
      displayName: 'AlexRey30',
      username: '@rey30verse',
      roleLine: 'Founder • Streamer • Designer',
      initials: 'R3',
      followers: '25.8K',
      level: 'Nv. 42',
      templatesCount: 2,
      artworksCount: 2,
      activeTemplateName: 'Deck Neon',
      equippedStyleName: 'Nebula',
      focusLabel: 'Baraja completa',
      activityLabel: 'Ultima edicion hoy 10:40',
    },
    editor: {
      activeTemplateId: 'template-preview-1',
      templateName: 'Deck Neon',
      styleId: 'nebula',
      artworkId: null,
      scope: 'deck',
      targetCard: null,
      targetSuit: null,
      targetModule: null,
      targetElement: null,
      zoom: 100,
      rotation: 0,
      offsetX: 0,
      offsetY: 0,
    },
    inventoryDecks: [
      {
        id: 'preview-market-1',
        name: 'Nebula Deck',
        description: 'Baraja premium equipada en preview.',
        price: 450,
        currency: 'coins',
        image: 'neon',
        type: 'deck',
        rarity: 'rare',
        ownedQuantity: 1,
        equipped: true,
        canEquip: true,
      },
    ],
  }
}

export function getPreviewGameSnapshot(roomId?: string): GameSnapshot {
  const resolvedRoomId = roomId ?? 'preview-room-alpha'
  const roomName = getPreviewRoomName(resolvedRoomId)

  return {
    matchId: `preview-match-${resolvedRoomId}`,
    roomId: resolvedRoomId,
    roomName,
    status: 'active',
    roundNumber: 4,
    trickNumber: 7,
    crownsReleased: true,
    leadSuit: 'diamonds',
    currentTurnSeat: 3,
    currentTurnLabel: 'Tu turno',
    summary: 'Vista previa de la mesa. La logica persistente requiere DB real para jugar completo.',
    ruleHint: 'Debes seguir el palo lider de diamantes en esta baza.',
    hand: [
      { id: 'diamonds-14', suit: 'diamonds', rank: 14, label: 'A' },
      { id: 'crowns-10', suit: 'crowns', rank: 10, label: '10' },
      { id: 'spades-12', suit: 'spades', rank: 12, label: 'Q' },
      { id: 'clubs-13', suit: 'clubs', rank: 13, label: 'K' },
      { id: 'diamonds-11', suit: 'diamonds', rank: 11, label: 'J' },
    ],
    playableCardIds: ['diamonds-14', 'diamonds-11'],
    tableCards: [
      { seat: 0, playerName: 'MiaBot', card: { id: 'diamonds-8', suit: 'diamonds', rank: 8, label: '8' } },
      { seat: 1, playerName: 'RexBot', card: { id: 'diamonds-9', suit: 'diamonds', rank: 9, label: '9' } },
      { seat: 2, playerName: 'NovaBot', card: { id: 'diamonds-13', suit: 'diamonds', rank: 13, label: 'K' } },
    ],
    tableMessages: [
      {
        id: 'preview-game-message-1',
        roomId: resolvedRoomId,
        user: { name: 'MiaBot', avatar: 'miabot' },
        content: 'Si cierras con A♦ te llevas la baza limpia.',
        timestamp: '10:27',
      },
      {
        id: 'preview-game-message-2',
        roomId: resolvedRoomId,
        user: { name: 'Yo', avatar: 'alexrey30', isMe: true },
        content: 'Voy con diamantes para no romper la regla.',
        timestamp: '10:28',
      },
    ],
    seats: [
      {
        seat: 0,
        name: 'MiaBot',
        avatar: 'miabot',
        score: 4,
        roundPoints: 1,
        tricksWon: 2,
        cardsRemaining: 6,
        isBot: true,
        isConnected: true,
        position: 'top',
      },
      {
        seat: 1,
        name: 'RexBot',
        avatar: 'rexbot',
        score: 12,
        roundPoints: 4,
        tricksWon: 1,
        cardsRemaining: 6,
        isBot: true,
        isConnected: true,
        position: 'left',
      },
      {
        seat: 2,
        name: 'NovaBot',
        avatar: 'novabot',
        score: 8,
        roundPoints: 2,
        tricksWon: 2,
        cardsRemaining: 6,
        isBot: true,
        isConnected: true,
        position: 'right',
      },
      {
        seat: 3,
        name: 'AlexRey30',
        avatar: 'alexrey30',
        score: 6,
        roundPoints: 0,
        tricksWon: 1,
        cardsRemaining: 5,
        isBot: false,
        isMe: true,
        isConnected: true,
        isTurn: true,
        position: 'bottom',
        statusLabel: 'Tu turno',
      },
    ],
    standings: [
      { seat: 0, name: 'MiaBot', score: 4, roundPoints: 1, tricksWon: 2 },
      { seat: 1, name: 'RexBot', score: 12, roundPoints: 4, tricksWon: 1 },
      { seat: 2, name: 'NovaBot', score: 8, roundPoints: 2, tricksWon: 2 },
      { seat: 3, name: 'AlexRey30', score: 6, roundPoints: 0, tricksWon: 1, isMe: true },
    ],
    recentEvents: [
      { id: 'preview-game-event-1', type: 'preview', summary: 'Mesa cargada en modo preview.', createdAt: '10:28' },
      { id: 'preview-game-event-2', type: 'play', summary: 'NovaBot tiro K♦.', createdAt: '10:29' },
      { id: 'preview-game-event-3', type: 'turn', summary: 'Tu mano esta lista para inspeccion.', createdAt: '10:30' },
    ],
    controls: {
      voiceEnabled: true,
      soundEnabled: true,
      tableChatEnabled: true,
      darkMode: true,
      tableZoom: 72,
      cardScale: 64,
    },
  }
}

export function getPreviewAppSnapshot(): AppSnapshot {
  const live = getPreviewLiveSnapshot()
  const market = getPreviewMarketplaceSnapshot()
  const customize = getPreviewCustomizationSnapshot()

  return {
    currentUser: {
      id: 'preview-user',
      displayName: 'AlexRey30',
      initials: 'AR',
      avatarSeed: 'alexrey30',
      level: 42,
      points: '12.4K',
      elo: '2350',
      rank: 'Top 12',
    },
    presence: getPreviewPresence({
      state: 'online',
      screen: 'home',
      latencyMs: 18,
    }),
    dashboard: {
      traction: {
        sessions: '9.4K',
        delta: '+18%',
      },
      timeline: [
        'Hub visual unificado listo para revisar.',
        'Chat, live, market y card lab tienen UI navegable.',
        'Snake es jugable localmente dentro del hub.',
        'La mesa persistente y el backend completo necesitan DB real.',
      ],
      storytellers: [
        { name: 'Mia', accent: 'from-fuchsia-500 to-violet-500' },
        { name: 'Rex', accent: 'from-cyan-500 to-sky-500' },
        { name: 'Nova', accent: 'from-pink-500 to-rose-500' },
        { name: 'Kira', accent: 'from-violet-500 to-indigo-500' },
        { name: 'Axel', accent: 'from-amber-400 to-orange-500' },
      ],
      liveChats: [
        { id: 'preview-dashboard-chat-1', room: 'Chat Global', note: '125 mensajes activos', accent: 'text-cyan-300', badge: '125' },
        { id: 'preview-dashboard-chat-2', room: 'Team Vikings', note: 'Torneo esta noche', accent: 'text-fuchsia-300', badge: '8' },
        { id: 'preview-dashboard-chat-3', room: 'Sala de Voz', note: '5 personas conectadas', accent: 'text-amber-300', badge: 'EN' },
      ],
      topMetrics: [
        { label: 'Puntos', value: '13', hint: 'Cada corazon vale 1' },
        { label: 'Victorias', value: '1,248', hint: 'Temporada actual' },
        { label: 'ELO', value: '2,350', hint: 'Competitivo' },
      ],
      activeRooms: [
        { id: 'preview-room-alpha', name: 'Mesa Preview Central', players: '3/4', cta: 'Entrar' },
        { id: 'preview-room-bots', name: 'Mesa vs Bots', players: '1/4', cta: 'Entrar' },
        { id: 'preview-room-ranked', name: 'Ranked Preview', players: '4/4', cta: 'Lleno' },
        { id: 'preview-room-private', name: 'Sala Privada Demo', players: '2/4', cta: 'Entrar' },
      ],
      chatFeed: [
        { id: 'preview-feed-1', user: 'Charlie', text: 'Buena suerte a todos' },
        { id: 'preview-feed-2', user: 'Mia', text: 'La reina cae esta ronda' },
        { id: 'preview-feed-3', user: 'AlexRey30', text: 'Revisando estado real del producto' },
      ],
      deckStyles: ['Nebula', 'Arcade', 'Aurora', 'Obsidian', 'Neon Ink', 'Royal Gold'],
      featuredStream: {
        id: live.activeStreamId ?? 'preview-stream-main',
        hostName: 'LunaGamer',
        hostInitials: 'LG',
        title: 'Preview del hub social gaming en vivo',
        subtitle: 'Evento: revision general del producto',
        viewers: '3.4K',
        comments: '342',
        reactions: '1.2K',
        highlightCards: ['A♠', '10♥', 'K♣', 'Q♦'],
      },
      profile: {
        displayName: 'AlexRey30',
        username: '@rey30verse',
        bio: 'Vista previa para revisar modulos, UX y brechas de producto.',
        following: '1.2K',
        followers: '25.8K',
        loves: '345K',
        statusItems: [
          'Preview navegable sin DB real.',
          'Snake funcional dentro del hub.',
          'Mesa completa pendiente de backend conectado.',
        ],
      },
      table: {
        roomName: 'Mesa Preview Central',
        top: { name: 'MiaBot', initials: 'MB', scoreLabel: '4 pts' },
        left: { name: 'RexBot', initials: 'RB', scoreLabel: '12 pts' },
        right: { name: 'NovaBot', initials: 'NB', scoreLabel: '8 pts' },
        bottom: { name: 'AlexRey30', initials: 'AR', scoreLabel: 'Tu turno', statusLabel: 'Preview jugable visual' },
        centerCards: ['8♦', '9♦', 'K♦'],
        handCards: ['A♦', '10♥', 'Q♠', 'K♣', 'J♦'],
        zoom: '72%',
        cardSize: '64%',
        darkMode: 'On',
      },
    },
    chat: {
      activeRoomId: 'preview-chat-global',
      rooms: [
        { id: 'preview-chat-global', name: 'Chat Global', type: 'global', lastMessage: 'Revision activa del hub', unread: 12, online: 342 },
        { id: 'preview-chat-luna', name: 'LunaGamer', type: 'private', avatar: 'lunagamer', lastMessage: '¿Jugamos despues?', unread: 2 },
        { id: 'preview-chat-team', name: 'Team Vikings', type: 'group', lastMessage: 'Torneo esta noche', unread: 5 },
        { id: 'preview-chat-room', name: 'Sala #42', type: 'game', lastMessage: 'Mesa en preview lista', unread: 1 },
      ],
      messages: [
        { id: 'preview-chat-message-1', roomId: 'preview-chat-global', user: { name: 'LunaGamer', avatar: 'lunagamer' }, content: 'Ya podemos revisar el hub completo.', timestamp: '10:30', reactions: ['❤️', '🔥'] },
        { id: 'preview-chat-message-2', roomId: 'preview-chat-global', user: { name: 'DarkKnight_X', avatar: 'darkknightx' }, content: 'Falta cerrar DB y test para produccion.', timestamp: '10:31' },
        { id: 'preview-chat-message-3', roomId: 'preview-chat-global', user: { name: 'Yo', avatar: 'alexrey30', isMe: true }, content: 'Perfecto, primero inspeccionamos todo lo actual.', timestamp: '10:32' },
        { id: 'preview-chat-message-4', roomId: 'preview-chat-luna', user: { name: 'LunaGamer', avatar: 'lunagamer' }, content: 'La UI del live ya se ve premium.', timestamp: '10:35' },
      ],
    },
    lobby: {
      rooms: [
        {
          id: 'preview-room-alpha',
          name: 'Mesa Preview Central',
          description: 'Mesa principal del hub con cuatro asientos y chat activo.',
          inviteCode: null,
          host: { name: 'CyberQueen', avatar: 'cyberqueen', level: 67 },
          players: 3,
          maxPlayers: 4,
          type: 'public',
          mode: 'normal',
          pointsRequired: 0,
          isRanked: false,
          voiceEnabled: true,
          isMember: false,
          isHost: false,
          isReadyByMe: false,
          readyCount: 2,
          humanPlayers: 3,
          canLaunch: false,
          requiresInvite: false,
          canViewInternals: true,
          status: 'waiting',
          activityLabel: 'Actividad hace 2 min',
          seats: [
            { id: 'preview-seat-1', name: 'CyberQueen', avatar: 'cyberqueen', isHost: true, isReady: true },
            { id: 'preview-seat-2', name: 'MiaGamer', avatar: 'miagamer', isReady: false },
            { id: 'preview-seat-3', name: 'AlexRey30', avatar: 'alexrey30', isReady: true },
          ],
          recentMessages: [
            {
              id: 'preview-room-alpha-message-1',
              roomId: 'preview-room-alpha',
              user: { name: 'CyberQueen', avatar: 'cyberqueen' },
              content: 'Checklist final antes de lanzar la mesa.',
              timestamp: '10:41',
            },
            {
              id: 'preview-room-alpha-message-2',
              roomId: 'preview-room-alpha',
              user: { name: 'Yo', avatar: 'alexrey30', isMe: true },
              content: 'Ya quedo lista la configuracion del lobby.',
              timestamp: '10:42',
            },
          ],
        },
        {
          id: 'preview-room-bots',
          name: 'Mesa vs Bots',
          description: 'Practica privada con tres bots y reinicio inmediato.',
          inviteCode: null,
          host: { name: 'MiaGamer', avatar: 'miagamer', level: 58 },
          players: 1,
          maxPlayers: 4,
          type: 'public',
          mode: 'normal',
          pointsRequired: 0,
          isRanked: false,
          voiceEnabled: false,
          isMember: false,
          isHost: false,
          isReadyByMe: false,
          readyCount: 1,
          humanPlayers: 1,
          canLaunch: true,
          requiresInvite: false,
          canViewInternals: true,
          status: 'waiting',
          bots: 3,
          activityLabel: 'Actividad hace 9 min',
          seats: [{ id: 'preview-seat-4', name: 'MiaGamer', avatar: 'miagamer', isHost: true, isReady: true }],
          recentMessages: [
            {
              id: 'preview-room-bots-message-1',
              roomId: 'preview-room-bots',
              user: { name: 'MiaGamer', avatar: 'miagamer' },
              content: 'Entreno rapido contra IA antes del ranked.',
              timestamp: '09:58',
            },
          ],
        },
        {
          id: 'preview-room-ranked',
          name: 'Ranked Preview',
          description: 'Mesa competitiva con requisito de puntos y voz activa.',
          inviteCode: null,
          host: { name: 'SamuraiQ', avatar: 'samuraiq', level: 44 },
          players: 4,
          maxPlayers: 4,
          type: 'public',
          mode: 'ranked',
          pointsRequired: 120,
          isRanked: true,
          voiceEnabled: true,
          isMember: false,
          isHost: false,
          isReadyByMe: false,
          readyCount: 4,
          humanPlayers: 4,
          canLaunch: true,
          requiresInvite: false,
          canViewInternals: true,
          status: 'full',
          activityLabel: 'Actividad hace 15 min',
          seats: [
            { id: 'preview-seat-5', name: 'SamuraiQ', avatar: 'samuraiq', isHost: true, isReady: true },
            { id: 'preview-seat-6', name: 'Nova', avatar: 'nova', isReady: true },
            { id: 'preview-seat-7', name: 'Kira', avatar: 'kira', isReady: true },
            { id: 'preview-seat-8', name: 'Axel', avatar: 'axel', isReady: true },
          ],
          recentMessages: [
            {
              id: 'preview-room-ranked-message-1',
              roomId: 'preview-room-ranked',
              user: { name: 'SamuraiQ', avatar: 'samuraiq' },
              content: 'Todos listos, arrancamos apenas cierre el bracket.',
              timestamp: '09:51',
            },
          ],
        },
        {
          id: 'preview-room-private',
          name: 'Sala Privada Demo',
          description: 'Sala cerrada para invitar equipo y probar manos personalizadas.',
          inviteCode: 'DEMO42',
          host: { name: 'NeonPlayer', avatar: 'neonplayer', level: 35 },
          players: 2,
          maxPlayers: 4,
          type: 'private',
          mode: 'tournament',
          pointsRequired: 200,
          isRanked: true,
          voiceEnabled: true,
          isMember: true,
          isHost: false,
          isReadyByMe: true,
          readyCount: 2,
          humanPlayers: 2,
          canLaunch: true,
          requiresInvite: false,
          canViewInternals: true,
          status: 'waiting',
          activityLabel: 'Actividad hace 1 h',
          seats: [
            { id: 'preview-seat-9', name: 'NeonPlayer', avatar: 'neonplayer', isHost: true, isReady: true },
            { id: 'preview-seat-10', name: 'AlexRey30', avatar: 'alexrey30', isReady: true },
          ],
          recentMessages: [
            {
              id: 'preview-room-private-message-1',
              roomId: 'preview-room-private',
              user: { name: 'NeonPlayer', avatar: 'neonplayer' },
              content: 'Pasa el codigo solo al squad y lanzamos.',
              timestamp: '09:14',
            },
            {
              id: 'preview-room-private-message-2',
              roomId: 'preview-room-private',
              user: { name: 'Yo', avatar: 'alexrey30', isMe: true },
              content: 'Listo, ya estoy dentro del lobby privado.',
              timestamp: '09:16',
            },
          ],
        },
      ],
    },
    game: getPreviewGameSnapshot(),
    live,
    market,
    customize,
    profile: {
      displayName: 'AlexRey30',
      username: 'rey30verse',
      roleLine: 'Founder • Streamer • Designer',
      bio: 'Preview navegable del estado actual del producto mientras conectamos base y flujos reales.',
      level: '42',
      wins: '1.2K',
      followers: '25.8K',
      points: '12.4K',
      initials: 'AR',
      achievements: ['🏆', '⭐', '💎', '🔥'],
      collection: ['♠', '♥', '♦', '♣'],
      roadmap: [
        'Conectar base de datos real en local y deploy.',
        'Eliminar mocks residuales del feed.',
        'Cubrir juego y APIs con tests.',
      ],
    },
  }
}
